project:
  type: website
  output-dir: docs
  
website:
  title: "Astrid Van Haren Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: 
        href: 
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Astrid Van Haren"

format:
  html:
    theme: cerulean, lilac
    toc: true

editor: source

